relativeURLs = true
disableKinds = ["taxonomy", "taxonomyTerm", "categories", "tags"]
author = "Luke Wood"
googleAnalytics=''

[params]
  #favicon = "/icons/rounded.png"
  description = "Boilerplate generated site"
